apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ferret
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ferret
        image: wasdev/ferret:1.1
        ports:
        - name: http
          containerPort: 9080
        readinessProbe:
          httpGet:
            path: /ferret
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
