version: '3'
services:
  web:
    image: dcurrie/mongodbapp
    ports:
     - "9080"
    networks:
     - mongo
    deploy:
     mode: replicated
     replicas: 2
     resources:
      limits:
       cpus: '0.5'
       memory: 512M
     restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
     update_config:
      parallelism: 1
      delay: 10s
      failure_action: continue
      monitor: 60s
      max_failure_ratio: 0.3
     placement:
      constraints: [node.role == worker]
    depends_on:
     - db
  db:
    image: mongo
    volumes:
     - db-data:/data/db
    networks:
     - mongo
    deploy:
     placement:
      constraints: [node.role == manager]
networks:
 mongo:
volumes:
 db-data:

